SELECT MVFORNEC.FORNECEDOR AS PD_IDCliFor,
RTRIM(SERIE) + RTRIM(CAST (NUMERO AS CHAR(8))) AS PD_Codigo,
'2' AS PD_IDOcorrencia,
'2' AS PD_PrazoAtivo,
RTRIM (CONVERT(char,DATTAEMISSAO,103)) AS PD_DmaPedido,
'1' AS PD_FaixaPreco,
'2' AS PD_SituacaoPedido,
MVITENS.ITEM AS PD_PedidoItem,
RTRIM (CAST (MVITENS.ALTERNATIVO AS CHAR(8))) AS PI_Codigo,
MVITENS.QUANTIDADE AS PI_Quant,
MVITENS.PRECOUNIT AS PI_Valor,
CASE WHEN MVITENS.BONIFICACAO = 'N' 
  THEN '1'
  ELSE '-1'
END AS PI_GeraReceita
from mv inner join mvitens on MV.SEQ = MVITENS.SEQNOTA
        inner join MVFORNEC on MV.SEQ = MVFORNEC.SEQNOTA
WHERE MV.FATO = 'SF'
ORDER BY DATTAEMISSAO