SELECT PRODUTOS.CODIGO, PRODUTOS.NOME, TRIBUTACAOPDV FROM TRIBUTACAO
INNER JOIN PRODUTOS
ON TRIBUTACAO.SEQPRODUTO = PRODUTOS.SEQ
WHERE TRIBUTACAO.FATO = 'PDV'
ORDER BY TRIBUTACAOPDV, PRODUTOS.NOME