-- QUERYS PARA SOMAR OS TOTAIS DAS VENDAS POR ITENS, ANALISANDO PELA CFOP E NCM.

-- CÓDIGO DE PRODUTOS, NOME DE PRODUTOS, NCM, CFOP E SOMA DOS ITENS
SELECT PRODUTOS.CODIGO, PRODUTOS.NOME, PRODUTOS.NBM AS NCM, MVITENS.CFOP, SUM(MVITENS.VALOR) AS VALOR_TOTAL FROM MVITENS
INNER JOIN PRODUTOS
ON MVITENS.ALTERNATIVO = PRODUTOS.CODIGO
INNER JOIN MV
ON MVITENS.SEQNOTA = MV.SEQ
WHERE MV.DATTAEMISSAO >= '2014-06-01' AND MV.DATTAEMISSAO <= '2014-06-30' AND MVITENS.CFOP >= '5000'
GROUP BY PRODUTOS.CODIGO, PRODUTOS.NOME,PRODUTOS.NBM, MVITENS.CFOP
ORDER BY PRODUTOS.NBM, MVITENS.CFOP

-- NCM, CFOP E SOMA DOS ITENS
SELECT PRODUTOS.NBM, MVITENS.CFOP, SUM(MVITENS.VALOR) AS VALOR_TOTAL FROM MVITENS
INNER JOIN PRODUTOS
ON MVITENS.ALTERNATIVO = PRODUTOS.CODIGO
INNER JOIN MV
ON MVITENS.SEQNOTA = MV.SEQ
WHERE MV.DATTAEMISSAO >= '2014-06-01' AND MV.DATTAEMISSAO <= '2014-06-30' AND MVITENS.CFOP >= '5000'
GROUP BY PRODUTOS.NBM, MVITENS.CFOP
ORDER BY PRODUTOS.NBM, MVITENS.CFOP

-- CFOP E SOMA DOS ITENS
SELECT MVITENS.CFOP, SUM(MVITENS.VALOR) AS VALOR_TOTAL FROM MVITENS
INNER JOIN MV
ON MVITENS.SEQNOTA = MV.SEQ
WHERE MV.DATTAEMISSAO >= '2014-06-01' AND MV.DATTAEMISSAO <= '2014-06-30' AND MVITENS.CFOP >= '5000'
GROUP BY MVITENS.CFOP
ORDER BY MVITENS.CFOP

-- NCM E SOMA DOS ITENS
SELECT PRODUTOS.NBM, SUM(MVITENS.VALOR) AS VALOR_TOTAL FROM MVITENS
INNER JOIN PRODUTOS
ON MVITENS.ALTERNATIVO = PRODUTOS.CODIGO
INNER JOIN MV
ON MVITENS.SEQNOTA = MV.SEQ
WHERE MV.DATTAEMISSAO >= '2014-06-01' AND MV.DATTAEMISSAO <= '2014-06-30' AND MVITENS.CFOP >= '5000'
GROUP BY PRODUTOS.NBM
ORDER BY PRODUTOS.NBM

SELECT MVITENS.CFOP, SUM(MV.DESCONTOVALOR) AS VALOR_DESC FROM MVITENS
INNER JOIN MV
ON MVITENS.SEQNOTA = MV.SEQ
WHERE MV.DATTAEMISSAO >= '2014-06-01' AND MV.DATTAEMISSAO <= '2014-06-30' AND MVITENS.CFOP >= '5000'
GROUP BY MVITENS.CFOP
ORDER BY MVITENS.CFOP
